### PR TITLE
Minimap size callback

### LINKED ISSUE #52: minimapPositionAndSize has incorrect width
**Describe the bug**
Because in baseCanvas/Canvas.tsx we set `width: 100%` in the HTML canvas, we don't actually use `props.canvasPositionAndSize` when setting canvas width. This makes sense because we need the canvas to be responsive to window resize (in fact I'm not sure how we get away with not using `height: %100` too?), but it means that there can be a discrepancy between a canvas's `canvasPositionAndSize` prop and the actual size. The spline and paintbrush base canvases are passed a callback to set `canvasPositionAndSize` on window resize so the main canvas has its position and size correct, but the minimap has no such callback, so there's a small discrepancy between its nominal width and actual width, which is causing the right edge of the viewfinder box to vanish off the edge of the canvas when in default zoom/pan configuration because the coord transform functions used to calculate its dimensions are using incorrect minimap width.

**To Reproduce**

1.  Load page
2.  Look at minimap

**Expected behavior**
A closed white box drawn around the image in the minimap.

### PR DESCRIPTION
**Pull request by philipjackson**
# Description

Added a `setMinimapPositionAndSize` callback to the minimap, analogous to the `setCanvasPositionAndSize` callback that the other canvases get. This fixes the missing right edge of the viewfinder box in the minimap when fully zoomed out.

closes #52

# Dependency changes

N/A

# Testing

N/A

# Documentation
N/A

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: src/ui.tsx [hunk 1]
```diff
@@ -167,13 +186,11 @@ export class UserInterface extends Component {
     this.setState({ brushSize: this.state.brushSize + 10 });
   };
 
- 
-  toggleEraser = ():void => {
-      this.setState({ activeTool: "eraser" });
+  toggleEraser = (): void => {
+    this.setState({ activeTool: "eraser" });
```
Comment (SilviaZeta) [inline src/ui.tsx:243]: this.setState({ activeTool: Tools.eraser }?

**Review by SilviaZeta — APPROVED** [review]

**Review by ChasNelson1990 — APPROVED** [review]
