### PR TITLE
Fix eraser

### LINKED ISSUE #349: Eraser Tool doesn't visually show what will be erased
## Describe the bug

Eraser tool no longer leaves a visual trail or mark, which makes it hard for the user to see what they are erasing. The bursh tool still does this.

## To Reproduce

Steps to reproduce the behaviour:

1.  Make annotation
2. Use eraser

## Expected behaviour

I would expect the eraser tool to act like the brush tool and create a visual trail or mark to indicate what will actually be erased.

## Screenshots

ezgif com-video-to-gif

## System Info (please complete the following information):

- OS: macOS Big Sur v11.5.2
- Browser: Google Chrome
- Browser version: Version 93.0.4577.63 (Official Build) (x86_64)

## Additional context

N/A

### PR DESCRIPTION
**Pull request by philipjackson**
## Description

Eraser strokes are now visible as they're being drawn, not just after. Also fixed a bug where erased portions become visible with translucency when the annotation is inactive.

closes #349 

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] New migrations have been committed
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] If appropriate, I have bumped any version numbers

### CODE REVIEW

File: src/toolboxes/paintbrush/Canvas.tsx [hunk 1]
```diff
@@ -235,7 +235,7 @@ export class CanvasClass extends Component<Props, State> {
       context.strokeStyle = brush.color;
       this.annotationOpacity = this.props.annotationAlpha;
     }
-    if (isActive || brush.type === "erase") {
```
Comment (SilviaZeta) [inline src/toolboxes/paintbrush/Canvas.tsx]: I think `isActive` here was added to apply the eraser only on the active annotation.

**Review by SilviaZeta — APPROVED** [review]

**Review by ChrisBaidoo — APPROVED** [review]
