### PR TITLE
fix: icon highlights

### LINKED ISSUE #282: Brush is on by default, by icon is not highlighted
When reloading a saved image, the brush function is already engaged without selecting it. The brush is not highlighted either.

### PR DESCRIPTION
**Pull request by philipjackson**
## Description

Fixes the green button highlights to work in a sensible and consistent way:

- The Paintbrush, Spline and Bounding Box buttons are highlighted if and only if the corresponding toolbox is active
- the `activeToolbox` state is now only used to specify which of Paintbrush, Spline and Bounding Box are active, this means you can have the Background toolbar open and still have Paintbrush activated and be able to draw.
- the `anchorElement` state is now used in a simpler way - it specifies which button's submenu is open, while also serving as the `anchorEl` prop for that submenu. It was kind of like this before but more explicitly so now I think. So the roles of `activeToolbox` and `anchorElement` are more clearly separated now; the former specifies which of the three annotation toolboxes is active, the latter says which submenu is open.
- `buttonClicked` is used a lot less - only for highlighting the submenu options in the Background toolbar now. It seems like the old behaviour was to remember the most recently clicked button so it can be highlighted, which seems confusing from a UX perspective because we also use highlights to indicate something is active, which seems more intuitive to me. If we do want that behaviour then let me know and I'll find some way to make it consistent, otherwise I'll gladly strip it out completely.

Also fixes the undo/redo buttons being constantly disabled.

closes #282 #460 

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] New migrations have been committed
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] If appropriate, I have bumped any version numbers

### CODE REVIEW

File: src/ui.tsx [hunk 1]
```diff
@@ -85,7 +85,7 @@ interface State {
   redraw: number;
   sliceIndex: number;
   channels: boolean[];
-  anchorElement: HTMLButtonElement | null; // A HTML element. It's used to set the position of the popover menu https://material-ui.com/api/menu/#props
+  anchorElement: HTMLButtonElement | null; // A HTML element. It specifies which button has its submenu open, and serves as anchorEl for that submenu: https://material-ui.com/api/menu/#props
```
Comment (ChasNelson1990) [inline src/ui.tsx:88]: Should we rename this then? Should we call it something like `activeSubmenuAnchor`?

**Review by ChasNelson1990 — APPROVED** [review]

File: src/ui.tsx (hunk 1 above)
Comment (philipjackson) [reply src/ui.tsx]: Yes.

**Review by ChasNelson1990 — APPROVED** [review]

**Review by ChrisBaidoo — APPROVED** [review]
